name: Pruebas API con Newman y reporte HTML

on:
  push:
    branches:
      - main

jobs:
  pruebas-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2.5.2

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas API
        run: |
          newman run https://api.getpostman.com/collections/22531503-08c7d3df-d134-46bf-914c-b7b224e3dd3d?apikey=${{ secrets.POSTMAN_API_KEY }} \
          --environment https://api.getpostman.com/environments/22531503-7eb70b23-1675-428c-aaff-8d2f6193c1db?apikey=${{ secrets.POSTMAN_API_KEY }} \
          --reporters cli,html \
          --reporter-html-export=./test-results/newman-results.html

      - name: Publicar reporte HTML
        uses: actions/upload-artifact@v2
        with:
          name: newman-results
          path: ./test-results/newman-results.html
