name: Newman Test Run
on:
  push:
    branches:
    - main
    - staging
jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
          collectionID: 22531503-08c7d3df-d134-46bf-914c-b7b224e3dd3d
          environmentID: 22531503-7eb70b23-1675-428c-aaff-8d2f6193c1db
      - run: npm install -g newman
      - run: newman run "https://api.getpostman.com/collections/${{collectionID}}?apikey=${{ secrets.POSTMAN_API_KEY }}" --environment "https://api.getpostman.com/environments/${{ environmentID }}?apikey=${{ secrets.POSTMAN_API_KEY }}"