name: OWASP ZAP scan
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-api-scan@v0.1.1
        with:
        target: 'https://www.zaproxy.org/'
