name: Test API with Postman

on: [push]

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Newman and dependencies
      run: |
        npm install -g newman
        npm install 
    - name: Run Postman collection
      run: |
        newman run newman/TaHouse.postman_collection.json -e newman/Ta_House.postman_environment.json -r cli,html